config/routes.rb
Differenzia::Application.routes.draw do
  
  get "deliveries/index"

  get "deliveries/show"

  get "csv/import"
  
  post "csv/import" => 'csv#upload'

  devise_for :users, :path_prefix => 'd'
  
  resources :users do
    member do
      get 'reset_password'
    end
  end

  get "dashboard/index"
  
  get "customers/search_full_name"
  
  resources :customers do
    resources :deliveries
  end
  
  resources :deliveries
  
  resources :products
  
  match 'render_select' => 'products#render_select'
  

  root :to => "dashboard#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :deliveries
	#cattr_reader :per_page
  #@@per_page = 10
  default_scope :order => 'full_name ASC'
  accepts_nested_attributes_for :deliveries
  
  def self.search_full_name(full_name)
    # http://erniemiller.org/projects/squeel/
    where(:full_name.matches => "%#{full_name}%")
  end
  
  def valid_square_meters
    (Settings.valid_square_meters >= square_meters) ? true : false
  end
end




# == Schema Information
#
# Table name: customers
#
#  id              :integer(10)     not null, primary key
#  year            :integer
#  full_name       :string(255)
#  birth_date      :date
#  address         :string(255)
#  number          :string(255)
#  postal_code     :string(255)
#  city            :string(255)
#  area            :string(255)
#  tax_code        :string(255)
#  contract_number :string(255)
#  square_meters   :integer
#  category        :integer
#  taxable_address :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  has_many :delivery_items
  has_many :products, :through => :delivery_items
  belongs_to :customer
  accepts_nested_attributes_for :delivery_items, :allow_destroy => true
end




# == Schema Information
#
# Table name: deliveries
#
#  id          :integer(10)     not null, primary key
#  customer_id :integer
#  notes       :text
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/delivery_item.rb
class DeliveryItem < ActiveRecord::Base
  belongs_to :delivery
  belongs_to :product
  #has_one :customer, :through => :delivery
end

# == Schema Information
#
# Table name: delivery_items
#
#  id          :integer(10)     not null, primary key
#  quantity    :integer
#  delivery_id :integer
#  product_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :delivery_items
  has_many :deliveries, :through => :delivery_items
end



# == Schema Information
#
# Table name: products
#
#  id          :integer(10)     not null, primary key
#  name        :string(255)
#  description :string(255)
#  quantity    :integer
#  unit_type   :string(255)
#  price       :decimal(8, 2)
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
	cattr_reader :per_page
  @@per_page = 10
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, 
         :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me, :role
  validate :role_in_list
  validates :first_name, :last_name, :email, :role, :presence => true
  ROLES = %w[admin manager user].freeze
  
  def role_in_list
    errors.add(:base, "Role #{self.role} is not allowed") unless User::ROLES.include?(self.role)
  end
end





# == Schema Information
#
# Table name: users
#
#  id                   :integer(10)     not null, primary key
#  email                :string(255)     default(""), not null
#  encrypted_password   :string(128)     default(""), not null
#  reset_password_token :string(255)
#  remember_token       :string(255)
#  remember_created_at  :datetime
#  sign_in_count        :integer         default(0)
#  current_sign_in_at   :datetime
#  last_sign_in_at      :datetime
#  current_sign_in_ip   :string(255)
#  last_sign_in_ip      :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  role                 :string(255)     default("user"), not null
#  first_name           :string(255)
#  last_name            :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
  protect_from_forgery
  helper_method :current_user_admin?
  layout :specify_layout
  
  private
  def specify_layout
    devise_controller? ? "sign" : "application"
  end
  
  def current_user_admin?
    @current_user.role == 'admin'
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  #layout :choose_layout
  
  def search_full_name
	  unless params[:customer_full_name].blank?
      full_name = params[:customer_full_name]
      @customers = Customer.search_full_name(full_name).page(params[:page]).per(Settings.customers_per_page)
    else
      @customers = Customer.all.page(params[:page]).per(Settings.customers_per_page)
    end
    render :layout => false if request.xhr?	  
	end
	
	def show
	  @customer = Customer.find(params[:id])
	  @delivery = @customer.deliveries.build
	  Settings.default_delivery.products.each { |product| @delivery.delivery_items.build(
	                                                      :product => Product.find_by_name(product.name),
	                                                      :quantity => product.quantity) }
	  #@products = Product.all
	  #@products_selected = []
	  #Settings.default_delivery.products.each{|product| @products_selected << product.id_value}
	  show!
	end

protected
  def collection
  	@customers ||= end_of_association_chain.page(params[:page]).per(Settings.customers_per_page)
  end
	
=begin	
	private
  def choose_layout
    if [ 'show' ].include? action_name
      'delivery'
    else
      'application'
    end
  end
=end  
		
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    
  def index
  end

end

app/controllers/deliveries_controller.rb
class DeliveriesController < InheritedResources::Base
=begin 
  def index
    @customer = Customer.find(params[:customer_id])
    @deliveries = Delivery.where("customer_id = ?", params[:customer_id])
  end

  def show
  end
  
  def create
    @delivery = Delivery.new(params[:delivery])
    if @delivery.save
      flash[:notice] = "New delivery created."
    else
      flash[:error] = "Error."
    end
    
    redirect_to customer_deliveries_url(params[:delivery][:customer_id])
  end
=end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  def render_select
    # render select box with products to be used in a new delivery creation
    @products = Product.all
    respond_to do |format|
      format.json { render :json => @products }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  def destroy
    begin
      @user = User.find(params[:id])
    rescue
      flash[:error] = "L'Operatore non può essere eliminato." 
    else
      flash[:notice] = "Operatore eliminato con successo." if @user.destroy
    end
    redirect_to users_url
  end
  
  def reset_password
    @user = User.find(params[:id])
    if @user.present?
      if @user.update_attributes(:user => { :password => 'password', :password_confirmation => 'password' })
        flash[:notice] = "La password è stata resettata."
      else
        flash[:notice] = "Errore: la password non è stata resettata."
      end
    end
    redirect_to users_url
  end
  
  protected
  def collection
  	@users ||= end_of_association_chain.page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)  
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")  
  end

  def link_to_add_fields(name, f, association)  
     new_object = f.object.class.reflect_on_association(association).klass.new  
     fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
       render(association.to_s.pluralize, :f => builder)
     end
     link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")  
  end  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_collection_table.html.haml
%table{:class => "#{collection.first.class.to_s.downcase.pluralize} collection"}
  %thead
    %tr
      - collection.first.attributes.each_pair do |field, value|
        - next if ['id', 'created_at', 'updated_at'].include?(field)
        %th= field.titleize
  %tbody
    - collection.each do |r|
      %tr
        - r.attributes.each_pair do |field, value|
          - next if ['id', 'created_at', 'updated_at'].include?(field)
          %td= value
        %td= link_to t('general.show'), resource_url(r)
        %td= link_to t('general.edit'), edit_resource_url(r)
        %td= link_to t('general.destroy'), resource_url(r), :confirm => t('general.are_you_sure'), :method => :delete

app/views/application/_edit_navigation.html.haml
%p= link_to "Show", resource_url(resource)
%p= link_to "Back", collection_url

app/views/application/_form.html.haml
= simple_form_for(resource, :as=> "#{resource_instance_name.to_s.downcase}",
  :url => resource.new_record? ? collection_url : resource_url(resource),
  :html => { :method => (resource.new_record? ? "post" : "put") }) do |f|
  /- if resource.errors.any?
  /  %tr
  /    %td{:colspan => "2"}
  /      %h2
  /        = pluralize(resource.errors.count, "error")
  /        prohibited this testa from being saved:
  /      %ul
  /        - resource.errors.full_messages.each do |msg|
  /          %li= msg
  - resource.attributes.each_pair do |field, value|
  - next if ['id', 'created_at', 'updated_at'].include?(field)
    = f.input field.to_sym
  = f.submit

app/views/application/_index_navigation.html.haml
%p= link_to t('general.new'), new_resource_url

app/views/application/_new_navigation.html.haml
%p= link_to "Back", collection_url

app/views/application/_resource_detail.html.haml
%table{:class => "#{collection.first.class.to_s.downcase} detail"}
  - resource.attributes.each_pair do |attr, value|
    - next if ['id', 'created_at', 'updated_at'].include?(attr)
    %tr
      %th= attr.titleize
      %td= value

app/views/application/_show_navigation.html.haml
%p= link_to "Edit", edit_resource_url(resource)
%p= link_to "Back", collection_url

app/views/application/edit.html.haml
/%h1
/  Edit #{resource.class.name.titleize}
= render "form"
= render "edit_navigation"

app/views/application/index.html.haml
= render "index_navigation"
- if collection.any?
  = render "collection_table"
= #will_paginate :previous_label => "« prec.", :next_label =>"succ. »"

app/views/application/new.html.haml
/%h1
/  New #{resource.class.name.titleize}
= render "form"
= render "new_navigation"

app/views/application/show.html.haml
= render "resource_detail"
= render "show_navigation"

app/views/customers/_customer.html.erb
<% if customer.valid_square_meters %>
  <tr class='alert'>
<% else %>
  <tr>
<% end %>    
  <td><%= customer.full_name %></td> 
  <td><%= l customer.birth_date %></td>
  <td><%= customer.tax_code %></td>
  <td><%= customer.address %></td>
  <td><%= customer.postal_code %></td>
  <td><%= customer.city %></td>
  <td><%= customer.area %></td>
  <td><%= customer.square_meters %></td>
  <td><%= link_to t('Details'), customer %></td>
</tr>

app/views/customers/_customer_head.html.haml
.list
  - if @customers.present?
    %p= page_entries_info
    %table
      %thead
        %tr
          %th= 'Nominativo'
          %th= 'Data di nascita'
          %th= 'Codice fiscale'
          %th= 'Indirizzo di residenza' 
          %th= 'Codice postale'
          %th= 'Città'
          %th= 'Prov.'        
          %th= 'Mq.'
          %th
      %tbody
        = render @customers
    %br
    = will_paginate :previous_label => "« prec.", :next_label =>"succ. »"

app/views/customers/_customer_table.html.haml
.list
  - if @customers.present?
    %table
      %thead
        %tr
          %th= t 'full_name'
          %th= t 'date_of_birth'
          %th= t 'SSN'
          %th= t 'address' 
          %th= t 'postal_code'
          %th= t 'city'
          %th= t 'area'        
          %th= t 'sq'
          %th
      %tbody
        = render @customers
    %br
    = paginate @customers

app/views/customers/_delivery_items.html.haml
%tr{:class => "fields"}
  %td{:class => "delivery_tbl"}
    = f.association :product, :label => false
  %td{:class => "delivery_tbl"}
    = f.input :quantity, :label => false
  %td{:class => "delivery_tbl"}
    = f.hidden_field :_destroy
    = link_to_remove_fields "remove", f

app/views/customers/_form.html.haml
= form_tag 'javascript:void(0)', :id => 'customer_search' do
	%p
		= label_tag :customer_full_name, t('full_name')
		= text_field_tag :customer_full_name, params[:customer_full_name]
		= image_tag("spinner.gif", :id => "spinner", :style => "display: none;")
%br

app/views/customers/_index_navigation.html.haml
/%p= link_to t('general.new'), new_resource_url

app/views/customers/_prova.html.haml
.list
  - if @total == 0
    %p Nessun risultato.....
  - elsif @customers
    %table
      %thead
        %tr
          %th= 'Nominativo'
          %th= 'Data di nascita'
          %th= 'Codice fiscale'
          %th= 'Indirizzo di residenza' 
          %th= 'Codice postale'
          %th= 'Città'
          %th= 'Prov.'        
          %th= 'Mq.'
          %th
      %tbody
        = render @customers
    %br
    = will_paginate :previous_label => "« prec.", :next_label =>"succ. »"

app/views/customers/index.html.haml
= render 'form' if !request.xhr?
#results
  = render "index_navigation"
  - if collection.any?
    = render "customer_table"

app/views/customers/search.html.haml
= render 'form' if !request.xhr?
#results
  = render "index_navigation"
  - if collection.any?
    = render "customer_table"

app/views/customers/search_full_name.html.haml
= render 'form' if !request.xhr?
#results
  = render "index_navigation"
  - if collection.any?
    = render "customer_table"

app/views/customers/show.html.haml
//= javascript_include_tag 'delivery_form'
.block
  .column.span-9
    %p Customer
    %p
      %label Anno:
      = @customer.year

    %p
      %label Nominativo:
      = @customer.full_name

    %p
      %label Data di nascita:
      = l @customer.birth_date if @customer.birth_date

    %p
      %label Indirizzo di residenza:
      = @customer.address

    %p
      %label Codice postale:
      = @customer.postal_code

    %p
      %label Città:
      = @customer.city

    %p
      %label Prov.:
      = @customer.area

    %p
      %label Codice fiscale:
      = @customer.tax_code

    %p
      %label Numero contratto:
      = @customer.contract_number

    %p
      %label Metri quadri:
      = @customer.square_meters

    %p
      %label Categoria:
      = @customer.category

    %p
      %label Indirizzo di riferimento:
      = @customer.taxable_address

    %br
    %p
      = link_to 'Indietro', "javascript:history.back()"
      
.block
  .column.span-15.last
    = render 'deliveries/form'

app/views/customers/show_bak.html.haml
.block
  /.column.span-4
  /  %div
  /    = render :partial => 'shared/menu'
  .column.span-24
    %p
      %b= 'Anno:'
      = @customer.year

    %p
      %b= 'Nominativo:'
      = @customer.full_name

    %p
      %b= 'Data di nascita:'
      - if @customer.birth_date
        = l @customer.birth_date    
      - else
        = @customer.birth_date

    %p
      %b= 'Indirizzo di residenza:'
      = @customer.address

    %p
      %b= 'Codice postale:'
      = @customer.postal_code

    %p
      %b= 'Città:'
      = @customer.city

    %p
      %b= 'Prov.:'
      = @customer.prov

    %p
      %b= 'Codice fiscale:'
      = @customer.tax_code

    %p
      %b= 'Numero contratto:'
      = @customer.contract_number

    %p
      %b= 'Metri quadri:'
      = @customer.square_meters

    %p
      %b= 'Categoria:'
      = @customer.category

    %p
      %b= 'Indirizzo di riferimento:'
      = @customer.taxable_address

    %br
    %p
      = link_to 'Indietro', "javascript:history.back()"

app/views/dashboard/index.html.haml
/= render 'form'
/%br
/#results

%hr
%h3 Available products:
%ul
  %li Green bags
  %li Red bags
  %li Blue bags
  
%hr
%h3 Latest product deliveries:
%ul
  %li Sign. X - 2011-04-05 15:33:33
  %li Sign. Y - 2011-04-05 15:33:33
  %li Sign. Z - 2011-04-05 15:33:33

app/views/deliveries/_delivery_item_fields.html.haml
%tr{:class => "fields"}
  %td{:class => "delivery_tbl"}
    = f.association :product, :label => false
  %td{:class => "delivery_tbl"}
    = f.input :quantity, :label => false
  %td{:class => "delivery_tbl"}
    = f.link_to_remove "remove"

app/views/deliveries/_delivery_items.html.haml
%tr{:class => "fields"}
  %td{:class => "delivery_tbl"}
    = f.association :product, :label => false
  %td{:class => "delivery_tbl"}
    = f.input :quantity, :label => false
  %td{:class => "delivery_tbl"}
    = f.hidden_field :_destroy
    = link_to_remove_fields "remove", f

app/views/deliveries/_form.html.haml
%p
  Delivery of: 
  = l Date.today

= simple_form_for @customer do |f|
  = f.simple_fields_for :deliveries do |delivery_f|
    %table{:class => "delivery_tbl"}
      %th products
      %th quantity
      = delivery_f.simple_fields_for :delivery_items do |item_f|
        = render 'deliveries/delivery_items', :f => item_f
    = link_to_add_fields "Add", delivery_f, :delivery_items
    = delivery_f.input :notes
  = f.submit

app/views/deliveries/_form_1.html.haml
%h2 
  New delivery
  = l Date.today
%p
  %a{:src => '#', :id => 'add_item'} Add item

#new_delivery
  
%input{:type => :hidden, :name => "delivery[customer_id]"}
%label Notes
%textarea{:name => "delivery[notes]"}
%p= submit_tag 'Save', :id => 'save_item'

%hr
%h2 Previous deliveries
%table
  %tr
    %th id
    %th created_at
  - @customer.deliveries.each do |delivery|
    %tr
      %td= delivery.id
      %td= delivery.created_at
      

app/views/deliveries/index.html.haml
.block
  .column.span-10
    %div
      /= render 'customers/show'
      %h3 Customer
      %p
        = @customer.full_name
        &ndash;
        = @customer.address
        &ndash;
        = @customer.city
        &ndash;
        = @customer.area
        &ndash;
        = @customer.postal_code
.block
  .column.span-14.last
    %div
      %hr/
      = simple_form_for Delivery.new do |f|
        = f.association :product
        = f.input :quantity
        = f.input :customer_id, :as => :hidden, :input_html => { :value => params[:customer_id] }
        = f.input :notes, :as => :string
        = f.button :submit
.block
  .column.span-24
    %div
      %hr/    
      %table
        %tr
          %th Product
          %th Quantity
          %th Delivered at
        - @deliveries.each do |d|
          %tr
            %td= d.product.name
            %td= d.quantity
            %td= d.created_at

app/views/deliveries/index_1.html.haml
.block
  .column.span-10
    %div
      /= render 'customers/show'
      %h3 Customer
      %p
        = @customer.full_name
        &ndash;
        = @customer.address
        &ndash;
        = @customer.city
        &ndash;
        = @customer.area
        &ndash;
        = @customer.postal_code
.block
  .column.span-14.last
    %div
      %hr/
      = simple_form_for Delivery.new do |f|
        = f.association :product
        = f.input :quantity
        = f.input :customer_id, :as => :hidden, :input_html => { :value => params[:customer_id] }
        = f.input :notes, :as => :string
        = f.button :submit
.block
  .column.span-24
    %div
      %hr/    
      %table
        %tr
          %th Product
          %th Quantity
          %th Delivered at
        - @deliveries.each do |d|
          %tr
            %td= d.product.name
            %td= d.quantity
            %td= d.created_at

app/views/deliveries/show.html.haml
%h1 Deliveries#show
%p Find me in app/views/deliveries/show.html.haml

app/views/deliveries/show_1.html.haml
%h1 Deliveries#show
%p Find me in app/views/deliveries/show.html.haml

app/views/inherited_resources_1/_collection_table.html.haml
%table{:class => "#{collection.first.class.to_s.downcase.pluralize} collection"}
  %thead
    %tr
      - collection.first.attributes.each_pair do |field, value|
        - next if ['id', 'created_at', 'updated_at'].include?(field)
        %th= field.titleize
  %tbody
    - collection.each do |r|
      %tr
        - r.attributes.each_pair do |field, value|
          - next if ['id', 'created_at', 'updated_at'].include?(field)
          %td= value
        %td= link_to t('general.show'), resource_url(r)
        %td= link_to t('general.edit'), edit_resource_url(r)
        %td= link_to t('general.destroy'), resource_url(r), :confirm => t('general.are_you_sure'), :method => :delete

app/views/inherited_resources_1/_edit_navigation.html.haml
%p= link_to "Show", resource_url(resource)
%p= link_to "Back", collection_url

app/views/inherited_resources_1/_form.html.haml
= simple_form_for(resource, :as=> "#{resource_instance_name.to_s.downcase}",
  :url => resource.new_record? ? collection_url : resource_url(resource),
  :html => { :method => (resource.new_record? ? "post" : "put") }) do |f|
  /- if resource.errors.any?
  /  %tr
  /    %td{:colspan => "2"}
  /      %h2
  /        = pluralize(resource.errors.count, "error")
  /        prohibited this testa from being saved:
  /      %ul
  /        - resource.errors.full_messages.each do |msg|
  /          %li= msg
  - resource.attributes.each_pair do |field, value|
  - next if ['id', 'created_at', 'updated_at'].include?(field)
    = f.input field.to_sym
  = f.submit

app/views/inherited_resources_1/_index_navigation.html.haml
%p= link_to t('general.new'), new_resource_url

app/views/inherited_resources_1/_new_navigation.html.haml
%p= link_to "Back", collection_url

app/views/inherited_resources_1/_resource_detail.html.haml
%table{:class => "#{collection.first.class.to_s.downcase} detail"}
  - resource.attributes.each_pair do |attr, value|
    - next if ['id', 'created_at', 'updated_at'].include?(attr)
    %tr
      %th= attr.titleize
      %td= value

app/views/inherited_resources_1/_show_navigation.html.haml
%p= link_to "Edit", edit_resource_url(resource)
%p= link_to "Back", collection_url

app/views/inherited_resources_1/edit.html.haml
/%h1
/  Edit #{resource.class.name.titleize}
= render "form"
= render "edit_navigation"

app/views/inherited_resources_1/index.html.haml
= render "index_navigation"
- if collection.any?
  = render "collection_table"
= #will_paginate :previous_label => "« prec.", :next_label =>"succ. »"

app/views/inherited_resources_1/new.html.haml
/%h1
/  New #{resource.class.name.titleize}
= render "form"
= render "new_navigation"

app/views/inherited_resources_1/show.html.haml
= render "resource_detail"
= render "show_navigation"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= (yield(:title).blank? ? "Differenzia" : "Differenzia - #{yield(:title)}")
    %meta{:name => "description", :content => "host-tastic support system"}
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    /////= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    /////= stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /////= stylesheet_link_tag 'compiled/app', :media => 'screen, projection'
    /[if lt IE 8]
      /////= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    /////= stylesheet_link_tag 'jquery.asmselect'
    /////= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"
    /////= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"
    /////= javascript_include_tag 'rails', 'application', 'searchbox', 'jquery.asmselect'
    = csrf_meta_tags
  %body
    #header
      %h1 Differenzia
      .user-details= render 'shared/user_details'
    .container
      .block
        .column.span-24
          %div
            %h2{:class => 'alt'}
              A simple product delivery software where operators can manage
              products, customers and stocks.
      .block
        .column.span-24
          %div
            - flash.each do |key, value|
              - unless value.blank?
                %div(class="#{key}")
                  = value
      .block
        .column.span-24
          #navigation
            = render_navigation(:level => 1) if user_signed_in?
        .block
          .column.span-24
            %div
              = yield
      .block
        .column.span-24
          %div
            %hr
            %em Copyright Mauro Sanna e Riccardo Tacconi

app/views/layouts/sign.html.haml
!!! 5
%html
  %head
    %title= (yield(:title).blank? ? "Differenzia" : "Differenzia - #{yield(:title)}")
    %meta{:name => "description", :content => "host-tastic support system"}
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'sign_in/sign'
    /////= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    /////= stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /////= stylesheet_link_tag 'compiled/devise', :media => 'screen, projection'
    /[if lt IE 8]
      /////= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    /////= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"
    /////= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"
    /////= javascript_include_tag 'rails', 'application'
    = csrf_meta_tags
    %body
      #header
        %h1 Differenzia
      .container
        .block
          .column.span-24
            = yield
        .block
          .column.span-24
            %hr
            %em Copyright Mauro Sanna e Riccardo Tacconi

app/views/shared/_menu.html.haml
.menu
  = link_to 'Dashboard', dashboard_index_url, :id => "dashboard"
  = link_to t('Customers'), customers_url, :id => 'customers'
  = link_to t('Products'), products_url, :id => 'customers'
  = link_to t('Users'), users_url, :id => 'operators' if current_user_admin?

app/views/shared/_user_details.html.haml
= current_user.email
&mdash; 
= "#{t 'users.role'}:"
= current_user.role
&mdash;
= link_to "Log out", destroy_user_session_url

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :first_name
  = f.input  :last_name
  = f.input :email
  = f.input :role, :collection => User::ROLES, :include_blank => false
  = f.input :password
  = f.input :password_confirmation
  %p= f.button :submit, :class => "button"

app/views/users/edit.html.haml
.column.span-20
  = render 'form'
  = link_to t('Back'), users_path

app/views/users/index.html.haml
.column.span-24
  .list
    %table
      %thead
        %tr
          %th= t 'users.first_name'
          %th= t 'users.last_name'
          %th Email
          %th= t 'users.role'
          %th= t 'created_at'
          %th &nbsp;
          %th &nbsp;
          %th &nbsp;
      %tbody    
        - @users.each do |user|
          %tr{:valign => "top", :class => cycle('odd', 'even')}
            %td= user.first_name
            %td= user.last_name
            %td= user.email
            %td= user.role
            %td= l user.created_at
            %td= link_to t('Edit'), edit_user_path(user)
            %td= link_to t('Destroy'), user, :confirm => t('general.are_you_sure'), :method => :delete
            %td= link_to 'Reset Password', reset_password_user_url(user)
  %br
  
  %p= link_to t('users.new_user'), new_user_path

app/views/users/new.html.haml
.column.span-20
  = render 'form'
  = link_to t('Back'), users_path